### PR TITLE
Bump crossSbtVersion & Cache dependencies

### PR DESCRIPTION
**Pull request by jiminhsieh**

### CODE REVIEW

**Comment by dwijnand** [comment]
I actually think it's better to cross-build against the lowest sbt version you can (within the version series).

For example with sbt-compat I cross-build against sbt 0.13.8: https://github.com/dwijnand/sbt-compat/blob/master/build.sbt#L14

So I think we should still target 1.0.0-RC3.

**Comment by jiminhsieh** [comment]
@dwijnand I see your point. How about 1.0.0? I think we could use production release version instead of RC(Release Candidate) version.

**Comment by dwijnand** [comment]
Yep, I'm happy with targeting 1.0.0.

**Comment by jiminhsieh** [comment]
Done. I changed crossSbtVersions to 1.0.0. :)

**Pull request merged**
