### PR TITLE
bintrayCredentials setting

### PR DESCRIPTION
**Pull request by jastice**
I got annoyed at having to write workarounds to publish things from CI (#25) so I implemented a `bintrayCredentials` setting that takes precedence over `bintrayCredentialsFile` if set. It changes the semantics of some of the tasks a bit, where they would previously prompt for credentials they might not now.

Just putting this up for comments for now, testing still outstanding.

### CODE REVIEW

**Comment by dwijnand** [comment]
See the discussion in still-open #69 about introducing a `Option[BintrayCredentials]` setting: https://github.com/sbt/sbt-bintray/pull/69#r54551869

**Comment by jastice** [comment]
well that was silly of me ~_~

**Comment by 2m** [comment]
Hi @jastice. Welcome to the club. :)

As discussed in the linked PR, the ideal solution would be to use sbt's `credentials` key. But that is tricky as then we get a dependency between some sbt settings in this plugin and tasks.

It is evident that the most needed functionality regarding bintray credentials is the ability to load the credentials from the env variables. This is especially useful in CI environments.

So instead of adding an additional setting we could refactor the code where [bintray credentials are loaded](https://github.com/sbt/sbt-bintray/blob/master/src/main/scala/Bintray.scala#L58) and make it try several different sources like we have [when loading pgp credentials](https://github.com/sbt/sbt-bintray/blob/master/src/main/scala/BintrayRepo.scala#L92).

WDYT?

**Comment by jvican** [comment]
Hey @jastice, I agree with @2m's proposed solution. Would you be up to update this PR with those changes?

**Comment by jastice** [comment]
@2m @jvican I think the reason both of us came up with the `bintrayCredentials` setting was that it was the obvious choice in how to make the credentials available to the existing settings and tasks, and `ensuredCredentials` wasn't even used consistently. OTOH, we could break some more compatibility to change this. I'll play around more with it when I have some leisure.

**Comment by 2m** [comment]
@jastice I have created a PR that makes `ensuredCredentials` consistently used and amended that function to also resolve credentials from props and env variables. https://github.com/sbt/sbt-bintray/pull/113
Let me know what you think.

**Comment by jastice** [comment]
@2m nice job, thanks!

**Pull request closed without merging**
