### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by slouc**
Added missing info about `binaryRepository` and `bintrayPackage` fields which cost me a couple of hours ;)

### CODE REVIEW

**Comment by dwijnand** [comment]
Looks like those are set in `bintrayPublishSettings` which are included when the plugin is enabled:

https://github.com/sbt/sbt-bintray/blob/456e57e91a8e94fdde6199279defb2df453a0c17/src/main/scala/BintrayPlugin.scala#L54-L62

So I don't understand what didn't work for you.

**Comment by slouc** [comment]
What does it mean to "enable" the plugin? I followed the readme and I had all bintray-related sbt commands working fine, so I figured it's enabled. I didn't see anything about "enabling" it though.

**Comment by dwijnand** [comment]
Yeah the plugin is auto-enabled. I was being too subtle, I meant unless you disabled it.

**Comment by slouc** [comment]
OK but then there's something going on, possibly a bug, because I had to add those lines explicitly.

**Comment by dwijnand** [comment]
Would you like to open an issue, following sbt's issue template (https://github.com/sbt/sbt/blob/1.0.x/ISSUE_TEMPLATE.md)? We can take it from there then.

**Comment by slouc** [comment]
OK, see https://github.com/sbt/sbt/issues/2995

**Comment by 2m** [comment]
This ticket was a result of a surprising behavior which was fixed in the latest release. Therefore this ticket can be closed.

**Comment by dwijnand** [comment]
Ok. Thanks, @2m.

**Pull request closed without merging**
